---
title: Puppy's Opvoeden 
subtitle: voor (ouders van) Perfectionisten
---

# Puppy Ophalen

**Nuttige Video's**

1. [Hondenschool Online](https://www.youtube.com/watch?v=_TgBqaQKA64&list=PLap7FepmcVoRRHnBiWJxGgd8EsTUEwZd3)
    * Welke spullen heb je nodig?
    * Hond ophalen / in de auto
    * Eerste momenten in huis (snuffelen, benchtraining)
1. [Hondenschool Online](https://www.youtube.com/watch?v=e5Dzx6FVT1o&list=PLap7FepmcVoRwd2GcHp9TIsJLooyuYwJz)
    * Welke spullen heb je nodig?
    * Hoe controleer je of je een gezonde pup ophaalt?
    * Hond ophalen / in de auto
    * Eerste momenten in huis (snuffelen, benchtraining)
    * Desensitisatie
    * Eerste nacht (alleen beneden)
1. [Zak George's Dog Training Revolution](https://www.youtube.com/watch?v=4Cndhfrx6CU&list=PLMssKIjsDxXl_ZXQgcHlEY_fC-yL5P76N)
    * Hond ophalen
    * Aanleren tuigje/riem
    * Desensitisatie
    * Loslaten van speeltjes
    * Eerste nacht (in een hotel)
1. [Zak George's Dog Training Revolution](https://youtu.be/0c-IjjzmS0E)
    * Eerste dag in huis (omgevingsmanagement)
    * Tweede nacht (op luchtbed beneden naast hond)
1. [McCann Dog Training](https://youtu.be/-vlo84vDSlY)
    * Welke spullen heb je nodig?
    * Hond ophalen / in de auto
    * Eerste momenten thuis
    * Bench training
    * Zindelijkheidstraining
    * Eerste nacht (naast bed)

**Samenvatting...**     
Zorg dat de minimale benodigdheden in huis zijn. Denk daarbij aan:

* Een plek voor de hond om veilig tot rust te komen. Dit kan een mand of bench zijn in een rustige ruimte. 
    * De hond heeft al veel prikkels te verwerken en hoeft dus niet direct in het midden van alle aandacht te staan. 
    * Je puppy is nog niet zindelijk is - een ruimte waar je makkelijk kunt dweilen is dus aan te beleven.
    * De plek om tot rust te komen hoeft niet al direct de definitieve plek te zijn. Het helpt uiteraard wel met de training als je de plek de eerste tijden hetzelfde kunt houden. Maar kijk ook naar wat je hond aangeeft! Waar gaat hij/zij graag liggen om tot rust te komen?
* Een knuffel/dekentje. 
    * Je krijgt sowieso al de nestdoek mee, maar maak een knusse/warme omgeving voor je hond. Honden zijn contactslapers, en hun nestgenootjes moeten ze nu missen. Een pluizige vervanger kan daar misschien een beetje bij helpen.
* Een puppy riempje/halsbandje. 
    * De hond is nog te klein om al de volwassen riem te dragen - die is zwaarder dan de pup!
* Eten voor de eerste dagen. 
    * Vraag welk voer de fokker geeft (farm food?) - het is verstandig om de eerste weken hetzelfde voer te blijven geven. Wederom heeft de pup al veel veranderingen te doorstaan als het eten goed gaat hoeft dat niet ook nog veranderd te worden.
* "Activiteiten"
    * Een speeltje. 
        * Nog **geen** balletjes - het is niet goed voor de gewrichten van de groeiende hond om daar de gehele tijd achter aan te rennen. Ookal vinden ze dat prima leuk om te doen. Je kunt beter denken aan een trekspeeltje of een knuffel. 
        * Let wel; puppys zijn nog erg sloperig - het hoeven dus geen dure speeltjes te zijn! Je kunt ook tweedehands knuffels in de kringloop vinden (zonder harde ogen/neuzen/...) en speeltjes op Marktplaats.
    * Puppy vriendelijke knaag 'snacks'. 
        * Denk daarbij aan de knaag speeltjes van Nylabone (die kunnen veilig afbrokkelen), een Kong (met/zonder vulling), Farm Food botten, of makkelijke snacks zoals konijnenoren etc.

# Opvoeding

## Wat?

Wat wil je dat de hond uiteindelijk kan?

- Mensen op 4 poten begroeten
- Stoppen met spelen/bijten
- Aan de lijn lopen
- Auto rijden
- Op een terrasje verblijven
- Vreemde dieren kennen
- Andere honden begroeten
- ... 

## Hoe?

- Positieve Beloning
- Negatieve Beloning
- Wat vind je hond echt leuk?

## Waar?

- Omgevingsmanagement


